### ISSUE TITLE
Unable to get private repository of organization

### ISSUE THREAD

**Issue by gelidus** [wercker/step-glide-install#7]
Glide cannot resolve private repository of my organization. The public key generated by Wercker is assigned to my account, and I have all access rights.

**Comment by kokaz** [comment]
Hi @gelidus, by default glide is fetching dependencies through http(s) instead of ssh. One fitting solution here is to replace all `http://` URL by ssh URL:

```yaml
- script:
    name: force "go get" over ssh
    code: git config --global url."git@github.com:".insteadOf "https://github.com/"
```

Let me know if this worked

**Comment by apinnecke** [comment]
This wasn't necessary for me. I followed this doc [here](https://github.com/Masterminds/glide/blob/master/docs/glide.yaml.md) and added a repo field to my glide.yml pointing to the git repo like this:

```yaml
package: github.com/BusyGifts/contracts
import:
- package: github.com/BusyGifts/common
  repo: git@github.com:BusyGifts/common
```
